//GET http://localhost:3000/services/filter/{"first":0,"rows":3,"filters":{"name":{"value":"","matchMode":""},"description":{"value":"","matchMode":""},"price":{"value":"","matchMode":""},"createdDate":{"value":{"start":"2023-02-02T22:30:49.429Z","end":"2023-02-02T22:30:49.429Z"},"matchMode":""}}}       
GET http://localhost:3000/agents/filter/{"first":0,"rows":3,"filters":{"name":{"value":"","matchMode":""},"email":{"value":"","matchMode":""},"phone":{"value":"","matchMode":""},"latitude":{"value":"","matchMode":""},"longitude":{"value":"","matchMode":""},"status":{"value":"","matchMode":""},"service":{"value":"","matchMode":""},"createdDate":{"value":{"start":"2023-02-02T23:29:47.949Z","end":"2023-02-02T23:29:47.949Z"},"matchMode":""}}}